#!/bin/bash

OLD=./testRepo1
NEW=./testRepo2

FROM=8202a143a36b186d7dc1e8b63aae56daa8eb0070
TO=7962dcb4c6b420af7b2130fbadb5137312f655da

cd $OLD

pwd

mapfile -t sha1 < <(git rev-list HEAD)

for i in "${!sha1[@]}"; do
   if [[ "${sha1[$i]}" = "$FROM" ]]; then
       FROM_INDEX=$i;
   fi
   if [[ "${sha1[$i]}" = "$TO" ]]; then
      TO_INDEX=$i;
   fi

done

for (( i=FROM_INDEX;i<=TO_INDEX;i++)) ; do
    git format-patch "${sha1[$i]}"~.."${sha1[$i]}";
done
    #if [ $sha1 = $FROM ] then
#	git format-patch $sha1~..$sha1
    #fi

    #if [ $sha1 = $TO ] then
#	git format-patch $sha1~..$sha1
#	break
#    fi


cd $NEW

pwd

#git am --signoff < <("$OLD"/*.patch)
patches="$OLD"/*.patch

for i in $patches; do
    #echo "$i"
    git am "$i"
done
