#!/bin/bash

set -e

OLD=/home/george/Desktop/CommitMover/testRepo1
NEW=/home/george/Desktop/CommitMover/testRepo2

FROM=7ffa778399fc6ea18e17784478519ef21492305c
TO=91b7c02334b1dd3eee183c4c561a3cde450413a5

# TESTING VARIABLES
#TO=05e74c0ccfc4754734568e9960dad16150060a04
#FROM=7962dcb4c6b420af7b2130fbadb5137312f655da

cd $OLD

pwd

mapfile -t sha1 < <(git rev-list HEAD)

#The indices are aquired in reverse order
for i in "${!sha1[@]}"; do
   if [[ "${sha1[$i]}" = "$FROM" ]]; then
       TO_INDEX=$i;
   fi
   if [[ "${sha1[$i]}" = "$TO" ]]; then
      FROM_INDEX=$i;
   fi

done

for (( i=FROM_INDEX;i<=TO_INDEX;i++)) ; do
    git format-patch "${sha1[$i]}"~.."${sha1[$i]}";
done
    #if [ $sha1 = $FROM ] then
#	git format-patch $sha1~..$sha1
    #fi

    #if [ $sha1 = $TO ] then
#	git format-patch $sha1~..$sha1
#	break
#    fi


cd $NEW

pwd

#git am --signoff < <("$OLD"/*.patch)
patches="$OLD"/*.patch

for i in $patches; do
    #echo "$i"
    git am "$i"
done
